// Wait for the DOM to load
document.addEventListener('DOMContentLoaded', () => {
    const button = document.getElementById('action-btn');
    const message = document.getElementById('message');

    // Add click event to the button
    button.addEventListener('click', () => {
        message.textContent = "Hello! This text was generated by JavaScript.";
        message.style.color = "green";
    });
});
